# The lookback window prior to visit date for each feature category. Records taken within this time window are valid.
trt_lookback_window: [-28, -1] # days
lab_lookback_window: [-7, -1] # days
symp_lookback_window: [-30, -1] # days
ed_visit_lookback_window: 5 # years
